owner: PortageApp
repo: portage-status

sites:
  - name: Portage System Health
    url: https://app.portage.so/api/health
    headers:
      - "x-healthcheck-secret: superlongrandomsecret"
    expectedStatusCodes: [200]
    maxResponseTime: 3000

status-website:
  cname: status.portage.so
  theme: dark
  logoUrl: https://cdn.prod.website-files.com/667f5e11c580564940534d04/68ca93bc501af19640f1fc2c_android-chrome-256x256.png
  name: Portage System Status
  introTitle: "Portage System Health"
  introMessage: "Check the status of the Portage App and its dependencies."
  favicon: https://cdn.prod.website-files.com/667f5e11c580564940534d04/68ca92d42f690d0fcd93adbb_favicon-32x32.png
  navbar:
    - title: Back to Website
      href: https://www.portage.so
    - title: Back to App
      href: https://app.portage.so
  meta:
    description: "Live system status and uptime metrics for the Portage strategy platform."
    ogTitle: "Portage Status"
    ogDescription: "Real-time uptime and incident history."

workflowSchedule:
  graphs: "0 * * * *" # hourly
  responseTime: "*/10 * * * *" # every 10 min
  uptime: "*/5 * * * *" # every 5 min
